import { PrototypeComponent } from "../prototype/prototype.component"

export const about = {
    sno : 1,
    title : 'About The Project',
    description : "<b>Problem Statement:</b> Creating a suitable metric to identify the ecological behaviour of students and help the educators evaluate the curriculum on how well it incorporates nature-based environment education and healthy behaviour among students.<br/><br/><b>Description:</b>The core idea behind this project is to assess individual student based on their ability to connect to environment and be knowledgeable of it, promote good environmental practices and also general healthy behaviour to help them become a green citizen of future.<br/><br/><p>The problem it solves is inadequate nature-based education that doesnot provide adequate examples and ability for students to connect with nature. Since they are future citizen, it is important such values are created from the fundamental important part in life - schools. This project provides for continuous assessment of individuals to identify ideas and promote nature-based innovations and also helps educators to model the curriculum for better outcome on nature-based behaviour parameters.</p>It gives a general consensus and statistical inference based on a pre-trained model based on data collected from student's activity.The solution is clearly stated and the project purpose and basic functionality are mapped to the opportunity area.<br/><br/><b>Reference journal:</b> <a href='https://www.journals.elsevier.com/global-environmental-change'>Global Environmental Change</a>"
}

export const instructions = {
    sno : 2,
    title : 'Instructions',
    description : "<p>The instructions given below are some details about the prototype environment made.</p><ul><li>The sample consist of 3 students - A, B, C who are students under the supervision of an Educator.</li><li>Educator will entry records of each of the student every day to state - <ul><li>The score gained on environment knowledge based question answer if any taken during the day.</li><li>Evaluation of activity done by the student during excursion undertaken by the educator in which the student took part.</li><li>Score given to the student for taking part in ECA related to environment.</li></ul></ul><p>The backend mathematical model of the system will evaluate the general environmental behaviour of the student, the knowledge gained by the student, the number ofa ctivites it undertook and how connected their behaviour is to environment friendly approach. The educators can evaluate their student based on monthly evaluation or annual evaluation to understand the student's overall outcome towards green citizen from the course he/she takes and which in turn can give a general idea of how aligned the course is in promoting sustainable environment.</p><p>Educators can then change their course based on the target evaluation score they expect from the student. It will greatly help in promote a wider nature-based environment education in the school system. </p>"
}